//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoft.Data.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalSoft.Data.Models.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мост.
        /// </summary>
        internal static string ChartType_Bridge {
            get {
                return ResourceManager.GetString("ChartType_Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коронка.
        /// </summary>
        internal static string ChartType_Crown {
            get {
                return ResourceManager.GetString("ChartType_Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коронка - ключ(зелен).
        /// </summary>
        internal static string ChartType_Crown_Key {
            get {
                return ResourceManager.GetString("ChartType_Crown_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имплант.
        /// </summary>
        internal static string ChartType_Implant {
            get {
                return ResourceManager.GetString("ChartType_Implant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсваща коронка.
        /// </summary>
        internal static string ChartType_MissingCrown {
            get {
                return ResourceManager.GetString("ChartType_MissingCrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсващ зъб.
        /// </summary>
        internal static string ChartType_MissingTooth {
            get {
                return ResourceManager.GetString("ChartType_MissingTooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частична протеза.
        /// </summary>
        internal static string ChartType_PartialProsthesis {
            get {
                return ResourceManager.GetString("ChartType_PartialProsthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Част от коронка.
        /// </summary>
        internal static string ChartType_PartOfCrown {
            get {
                return ResourceManager.GetString("ChartType_PartOfCrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Част от коронка - мрежа.
        /// </summary>
        internal static string ChartType_PartOfCrown_Grid {
            get {
                return ResourceManager.GetString("ChartType_PartOfCrown_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Част от корена.
        /// </summary>
        internal static string ChartType_PartOfRoot {
            get {
                return ResourceManager.GetString("ChartType_PartOfRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щифт.
        /// </summary>
        internal static string ChartType_Pin {
            get {
                return ResourceManager.GetString("ChartType_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тотална протеза.
        /// </summary>
        internal static string ChartType_Prosthesis {
            get {
                return ResourceManager.GetString("ChartType_Prosthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корен.
        /// </summary>
        internal static string ChartType_Root {
            get {
                return ResourceManager.GetString("ChartType_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черно.
        /// </summary>
        internal static string ColorType_Black {
            get {
                return ResourceManager.GetString("ColorType_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синьо.
        /// </summary>
        internal static string ColorType_Blue {
            get {
                return ResourceManager.GetString("ColorType_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тъмно синьо.
        /// </summary>
        internal static string ColorType_DarkBlue {
            get {
                return ResourceManager.GetString("ColorType_DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зелено.
        /// </summary>
        internal static string ColorType_Green {
            get {
                return ResourceManager.GetString("ColorType_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лилаво.
        /// </summary>
        internal static string ColorType_Purple {
            get {
                return ResourceManager.GetString("ColorType_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Червено.
        /// </summary>
        internal static string ColorType_Red {
            get {
                return ResourceManager.GetString("ColorType_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долу.
        /// </summary>
        internal static string PositionType_Bottom {
            get {
                return ResourceManager.GetString("PositionType_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горе.
        /// </summary>
        internal static string PositionType_Top {
            get {
                return ResourceManager.GetString("PositionType_Top", resourceCulture);
            }
        }
    }
}
