//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoft.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalSoft.Web.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоматолог.
        /// </summary>
        public static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагнози.
        /// </summary>
        public static string Diagnoses {
            get {
                return ResourceManager.GetString("Diagnoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагноза.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова Диагноза.
        /// </summary>
        public static string Diagnosis_NewDiagnosis {
            get {
                return ResourceManager.GetString("Diagnosis_NewDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артроза.
        /// </summary>
        public static string ExtraStatus_Artroza {
            get {
                return ResourceManager.GetString("ExtraStatus_Artroza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локсация.
        /// </summary>
        public static string ExtraStatus_Loksacia {
            get {
                return ResourceManager.GetString("ExtraStatus_Loksacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Н. Фациалис.
        /// </summary>
        public static string ExtraStatus_NFacialis {
            get {
                return ResourceManager.GetString("ExtraStatus_NFacialis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Н. Тригеминус.
        /// </summary>
        public static string ExtraStatus_NTrigeminus {
            get {
                return ResourceManager.GetString("ExtraStatus_NTrigeminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симетрия.
        /// </summary>
        public static string ExtraStatus_Simetria {
            get {
                return ResourceManager.GetString("ExtraStatus_Simetria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стави.
        /// </summary>
        public static string ExtraStatus_Stavi {
            get {
                return ResourceManager.GetString("ExtraStatus_Stavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сублоксация.
        /// </summary>
        public static string ExtraStatus_SubLoksacia {
            get {
                return ResourceManager.GetString("ExtraStatus_SubLoksacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парастезия.
        /// </summary>
        public static string ExtraStatus_TParastezia {
            get {
                return ResourceManager.GetString("ExtraStatus_TParastezia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пареза.
        /// </summary>
        public static string ExtraStatus_TPareza {
            get {
                return ResourceManager.GetString("ExtraStatus_TPareza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адреса е с невалиден формат.
        /// </summary>
        public static string Login_EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("Login_EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string Login_EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Login_EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидни данни.
        /// </summary>
        public static string Login_Invalidloginattempt {
            get {
                return ResourceManager.GetString("Login_Invalidloginattempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login_LogIn {
            get {
                return ResourceManager.GetString("Login_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string Login_PaswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Login_PaswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни паролата?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациент.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общ Статус.
        /// </summary>
        public static string Patient_BaseStatus {
            get {
                return ResourceManager.GetString("Patient_BaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КТ 3D.
        /// </summary>
        public static string Patient_CT {
            get {
                return ResourceManager.GetString("Patient_CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е.
        /// </summary>
        public static string Patient_ExtraoralsImages {
            get {
                return ResourceManager.GetString("Patient_ExtraoralsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансов план.
        /// </summary>
        public static string Patient_FinancialPlan {
            get {
                return ResourceManager.GetString("Patient_FinancialPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        public static string Patient_IntraoralsImages {
            get {
                return ResourceManager.GetString("Patient_IntraoralsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов Пациент.
        /// </summary>
        public static string Patient_NewPacient {
            get {
                return ResourceManager.GetString("Patient_NewPacient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОПГ.
        /// </summary>
        public static string Patient_OPG {
            get {
                return ResourceManager.GetString("Patient_OPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лични Данни.
        /// </summary>
        public static string Patient_PersonalData {
            get {
                return ResourceManager.GetString("Patient_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери.
        /// </summary>
        public static string Patient_Status_Select {
            get {
                return ResourceManager.GetString("Patient_Status_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р.
        /// </summary>
        public static string Patient_XrayImages {
            get {
                return ResourceManager.GetString("Patient_XrayImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екстраорален Статус.
        /// </summary>
        public static string Patient_ЕкстрапраленСтатус {
            get {
                return ResourceManager.GetString("Patient_ЕкстрапраленСтатус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зъбен Статус.
        /// </summary>
        public static string Patient_ЗъбенСтатус {
            get {
                return ResourceManager.GetString("Patient_ЗъбенСтатус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интраорален Статус.
        /// </summary>
        public static string Patient_ИнтраораленСтатус {
            get {
                return ResourceManager.GetString("Patient_ИнтраораленСтатус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парадонтален Статус.
        /// </summary>
        public static string Patient_ПарадонталенСтатус {
            get {
                return ResourceManager.GetString("Patient_ПарадонталенСтатус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на снимка.
        /// </summary>
        public static string PatientModel_AddImage {
            get {
                return ResourceManager.GetString("PatientModel_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациенти.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Млечни зъби.
        /// </summary>
        public static string PersonalData_HasDeciduousTeeth {
            get {
                return ResourceManager.GetString("PersonalData_HasDeciduousTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Първичен пациент.
        /// </summary>
        public static string PersonalData_PrimaryPatient {
            get {
                return ResourceManager.GetString("PersonalData_PrimaryPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери Град/Село.
        /// </summary>
        public static string PersonalDataModel_SelectLocation {
            get {
                return ResourceManager.GetString("PersonalDataModel_SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери Община.
        /// </summary>
        public static string PersonalDataModel_SelectMunicipality {
            get {
                return ResourceManager.GetString("PersonalDataModel_SelectMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери Област.
        /// </summary>
        public static string PersonalDataModel_SelectRegion {
            get {
                return ResourceManager.GetString("PersonalDataModel_SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел. указател.
        /// </summary>
        public static string Phonebook {
            get {
                return ResourceManager.GetString("Phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова категория.
        /// </summary>
        public static string Phonebook_NewCategory {
            get {
                return ResourceManager.GetString("Phonebook_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string Phonebook_NewCategoryIsRequired {
            get {
                return ResourceManager.GetString("Phonebook_NewCategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов контакт.
        /// </summary>
        public static string Phonebook_NewContact {
            get {
                return ResourceManager.GetString("Phonebook_NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А.
        /// </summary>
        public static string Plan_Agenda {
            get {
                return ResourceManager.GetString("Plan_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Д.
        /// </summary>
        public static string Plan_Day {
            get {
                return ResourceManager.GetString("Plan_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to М.
        /// </summary>
        public static string Plan_Month {
            get {
                return ResourceManager.GetString("Plan_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов.
        /// </summary>
        public static string Plan_NewPatient {
            get {
                return ResourceManager.GetString("Plan_NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часът не беше копиран.
        /// </summary>
        public static string Plan_NoItemCopied {
            get {
                return ResourceManager.GetString("Plan_NoItemCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително!.
        /// </summary>
        public static string Plan_RequiredField {
            get {
                return ResourceManager.GetString("Plan_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т.
        /// </summary>
        public static string Plan_Timeline {
            get {
                return ResourceManager.GetString("Plan_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        public static string Plan_Week {
            get {
                return ResourceManager.GetString("Plan_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р. С.
        /// </summary>
        public static string Plan_WorkWeek {
            get {
                return ResourceManager.GetString("Plan_WorkWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л.
        /// </summary>
        public static string ShortLeft {
            get {
                return ResourceManager.GetString("ShortLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д.
        /// </summary>
        public static string ShortRight {
            get {
                return ResourceManager.GetString("ShortRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтър по избрани зъби.
        /// </summary>
        public static string TeethStatus_FilterByTeeth {
            get {
                return ResourceManager.GetString("TeethStatus_FilterByTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зъб.
        /// </summary>
        public static string Tooth {
            get {
                return ResourceManager.GetString("Tooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ново Лечение.
        /// </summary>
        public static string Treatment_NewTreatment {
            get {
                return ResourceManager.GetString("Treatment_NewTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечения.
        /// </summary>
        public static string Treatments {
            get {
                return ResourceManager.GetString("Treatments", resourceCulture);
            }
        }
    }
}
