//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalSoft.Data.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DentalSoft.Data.Contracts.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стом..
        /// </summary>
        public static string Contacts_Dentist {
            get {
                return ResourceManager.GetString("Contacts_Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Contacts_Email {
            get {
                return ResourceManager.GetString("Contacts_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адреса е с невалиден формат.
        /// </summary>
        public static string Contacts_EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("Contacts_EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string Contacts_Fax {
            get {
                return ResourceManager.GetString("Contacts_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Contacts_FirstName {
            get {
                return ResourceManager.GetString("Contacts_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string Contacts_FirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Contacts_FirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Contacts_LastName {
            get {
                return ResourceManager.GetString("Contacts_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to М. Телефон.
        /// </summary>
        public static string Contacts_MobileTelephone {
            get {
                return ResourceManager.GetString("Contacts_MobileTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string Contacts_SecondName {
            get {
                return ResourceManager.GetString("Contacts_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Contacts_Telephone {
            get {
                return ResourceManager.GetString("Contacts_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Diagnosis_Code {
            get {
                return ResourceManager.GetString("Diagnosis_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагноза.
        /// </summary>
        public static string Diagnosis_Description {
            get {
                return ResourceManager.GetString("Diagnosis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимост.
        /// </summary>
        public static string Diagnosis_IsVisible {
            get {
                return ResourceManager.GetString("Diagnosis_IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуализация.
        /// </summary>
        public static string Diagnosis_Visualization {
            get {
                return ResourceManager.GetString("Diagnosis_Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string DiagnosisModel_CodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DiagnosisModel_CodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string DiagnosisModel_DescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DiagnosisModel_DescriptionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парастезия.
        /// </summary>
        public static string ExtraStatus_FParastezia {
            get {
                return ResourceManager.GetString("ExtraStatus_FParastezia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пареза.
        /// </summary>
        public static string ExtraStatus_FPareza {
            get {
                return ResourceManager.GetString("ExtraStatus_FPareza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожа.
        /// </summary>
        public static string ExtraStatus_Koja {
            get {
                return ResourceManager.GetString("ExtraStatus_Koja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицева симетрия.
        /// </summary>
        public static string ExtraStatus_LicevaSimetria {
            get {
                return ResourceManager.GetString("ExtraStatus_LicevaSimetria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЛВ.
        /// </summary>
        public static string ExtraStatus_RVL {
            get {
                return ResourceManager.GetString("ExtraStatus_RVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТДМ.
        /// </summary>
        public static string ExtraStatus_TDM {
            get {
                return ResourceManager.GetString("ExtraStatus_TDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тризмус.
        /// </summary>
        public static string ExtraStatus_Trizmus {
            get {
                return ResourceManager.GetString("ExtraStatus_Trizmus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устни.
        /// </summary>
        public static string ExtraStatus_Ustni {
            get {
                return ResourceManager.GetString("ExtraStatus_Ustni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. информация.
        /// </summary>
        public static string GeneralStatus_AdditionalInfo {
            get {
                return ResourceManager.GetString("GeneralStatus_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алергии.
        /// </summary>
        public static string GeneralStatus_Alergii {
            get {
                return ResourceManager.GetString("GeneralStatus_Alergii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бременност.
        /// </summary>
        public static string GeneralStatus_Bremennost {
            get {
                return ResourceManager.GetString("GeneralStatus_Bremennost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диабет.
        /// </summary>
        public static string GeneralStatus_Diabet {
            get {
                return ResourceManager.GetString("GeneralStatus_Diabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хипертония.
        /// </summary>
        public static string GeneralStatus_Hipertonia {
            get {
                return ResourceManager.GetString("GeneralStatus_Hipertonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфаркт.
        /// </summary>
        public static string GeneralStatus_Infarct {
            get {
                return ResourceManager.GetString("GeneralStatus_Infarct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инсулт.
        /// </summary>
        public static string GeneralStatus_Insult {
            get {
                return ResourceManager.GetString("GeneralStatus_Insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онкологични заб..
        /// </summary>
        public static string GeneralStatus_OnkologichniZab {
            get {
                return ResourceManager.GetString("GeneralStatus_OnkologichniZab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. информация.
        /// </summary>
        public static string Operation_AdditionalInfo {
            get {
                return ResourceManager.GetString("Operation_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стом..
        /// </summary>
        public static string Operation_Dentist {
            get {
                return ResourceManager.GetString("Operation_Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string Operation_DentistRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Operation_DentistRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагноза.
        /// </summary>
        public static string Operation_Diagnosis {
            get {
                return ResourceManager.GetString("Operation_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на диагнозата.
        /// </summary>
        public static string Operation_DiagnosisDateTime {
            get {
                return ResourceManager.GetString("Operation_DiagnosisDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string Operation_DiagnosisRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Operation_DiagnosisRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция.
        /// </summary>
        public static string Operation_Position {
            get {
                return ResourceManager.GetString("Operation_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бр..
        /// </summary>
        public static string Operation_Quantity {
            get {
                return ResourceManager.GetString("Operation_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зъби.
        /// </summary>
        public static string Operation_Teeth {
            get {
                return ResourceManager.GetString("Operation_Teeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зъб.
        /// </summary>
        public static string Operation_Tooth {
            get {
                return ResourceManager.GetString("Operation_Tooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string Operation_ToothRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Operation_ToothRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечение.
        /// </summary>
        public static string Operation_Treatment {
            get {
                return ResourceManager.GetString("Operation_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на лечението.
        /// </summary>
        public static string Operation_TreatmentDateTime {
            get {
                return ResourceManager.GetString("Operation_TreatmentDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Години.
        /// </summary>
        public static string PersonalData_Age {
            get {
                return ResourceManager.GetString("PersonalData_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ап..
        /// </summary>
        public static string PersonalData_Apt {
            get {
                return ResourceManager.GetString("PersonalData_Apt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блок.
        /// </summary>
        public static string PersonalData_Building {
            get {
                return ResourceManager.GetString("PersonalData_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата раждане.
        /// </summary>
        public static string PersonalData_DateOfBirth {
            get {
                return ResourceManager.GetString("PersonalData_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоматолог.
        /// </summary>
        public static string PersonalData_Dentist {
            get {
                return ResourceManager.GetString("PersonalData_Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string PersonalData_EGN {
            get {
                return ResourceManager.GetString("PersonalData_EGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string PersonalData_Email {
            get {
                return ResourceManager.GetString("PersonalData_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string PersonalData_Entrance {
            get {
                return ResourceManager.GetString("PersonalData_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string PersonalData_Fax {
            get {
                return ResourceManager.GetString("PersonalData_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string PersonalData_FirstName {
            get {
                return ResourceManager.GetString("PersonalData_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етаж.
        /// </summary>
        public static string PersonalData_Floor {
            get {
                return ResourceManager.GetString("PersonalData_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string PersonalData_Gender {
            get {
                return ResourceManager.GetString("PersonalData_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        public static string PersonalData_GP {
            get {
                return ResourceManager.GetString("PersonalData_GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осигурен.
        /// </summary>
        public static string PersonalData_HealthStatus {
            get {
                return ResourceManager.GetString("PersonalData_HealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишен стоматолог.
        /// </summary>
        public static string PersonalData_LastDentist {
            get {
                return ResourceManager.GetString("PersonalData_LastDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string PersonalData_LastName {
            get {
                return ResourceManager.GetString("PersonalData_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населено място.
        /// </summary>
        public static string PersonalData_Location {
            get {
                return ResourceManager.GetString("PersonalData_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобилен телефон.
        /// </summary>
        public static string PersonalData_MobileTelephone {
            get {
                return ResourceManager.GetString("PersonalData_MobileTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Община.
        /// </summary>
        public static string PersonalData_Municipality {
            get {
                return ResourceManager.GetString("PersonalData_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданство.
        /// </summary>
        public static string PersonalData_Nationality {
            get {
                return ResourceManager.GetString("PersonalData_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПП.
        /// </summary>
        public static string PersonalData_NextMedicalCheckUp {
            get {
                return ResourceManager.GetString("PersonalData_NextMedicalCheckUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No:.
        /// </summary>
        public static string PersonalData_NumberStreet {
            get {
                return ResourceManager.GetString("PersonalData_NumberStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Първичен пациент.
        /// </summary>
        public static string PersonalData_PrimaryPatient {
            get {
                return ResourceManager.GetString("PersonalData_PrimaryPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Област.
        /// </summary>
        public static string PersonalData_Region {
            get {
                return ResourceManager.GetString("PersonalData_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал.
        /// </summary>
        public static string PersonalData_ResidentialQuarter {
            get {
                return ResourceManager.GetString("PersonalData_ResidentialQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string PersonalData_SecondName {
            get {
                return ResourceManager.GetString("PersonalData_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string PersonalData_Street {
            get {
                return ResourceManager.GetString("PersonalData_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PersonalData_Telephone {
            get {
                return ResourceManager.GetString("PersonalData_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощ. код.
        /// </summary>
        public static string PersonalData_ZipCode {
            get {
                return ResourceManager.GetString("PersonalData_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string PersonalDataModel_DentistRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PersonalDataModel_DentistRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адреса е с невалиден формат.
        /// </summary>
        public static string PersonalDataModel_EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("PersonalDataModel_EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string PersonalDataModel_FirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PersonalDataModel_FirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string PersonalDataModel_LastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PersonalDataModel_LastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string PlanningItem_DentistRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PlanningItem_DentistRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string PlanningItem_PatientRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PlanningItem_PatientRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Treatment_Code {
            get {
                return ResourceManager.GetString("Treatment_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечение.
        /// </summary>
        public static string Treatment_Description {
            get {
                return ResourceManager.GetString("Treatment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимост.
        /// </summary>
        public static string Treatment_IsVisible {
            get {
                return ResourceManager.GetString("Treatment_IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Treatment_Price {
            get {
                return ResourceManager.GetString("Treatment_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуализация.
        /// </summary>
        public static string Treatment_Visualization {
            get {
                return ResourceManager.GetString("Treatment_Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string TreatmentModel_CodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TreatmentModel_CodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително.
        /// </summary>
        public static string TreatmentModel_DescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TreatmentModel_DescriptionRequiredErrorMessage", resourceCulture);
            }
        }
    }
}
